// examples/app-router-example/src/components/Counter.tsx
'use client'

import { useState } from 'react'

export default function Counter() {
  const [count, setCount] = useState(0)

  return (
    <div className="bg-white p-8 rounded-lg border-2 border-blue-600 text-center">
      <h2 className="text-blue-600 mb-4 text-2xl font-semibold">
        Interactive Counter (Client Component)
      </h2>
      <p className="text-5xl my-4 font-bold text-cyan-600">
        {count}
      </p>
      <div className="flex gap-4 justify-center">
        <button
          onClick={() => setCount(count - 1)}
          className="px-6 py-3 text-base bg-cyan-600 text-white border-none rounded cursor-pointer hover:bg-cyan-700 transition-colors"
        >
          Decrement
        </button>
        <button
          onClick={() => setCount(0)}
          className="px-6 py-3 text-base bg-gray-600 text-white border-none rounded cursor-pointer hover:bg-gray-700 transition-colors"
        >
          Reset
        </button>
        <button
          onClick={() => setCount(count + 1)}
          className="px-6 py-3 text-base bg-blue-600 text-white border-none rounded cursor-pointer hover:bg-blue-700 transition-colors"
        >
          Increment
        </button>
      </div>
      <p className="mt-4 text-gray-600 text-sm">
        This component runs on the client and maintains state
      </p>
    </div>
  )
}

// examples/qwik-bench/src/components/Counter.tsx
import { component$, useSignal } from '@qwik.dev/core'

export default component$(() => {
  const count = useSignal(0)

  return (
    <div class="p-6 border border-gray-300 rounded-lg bg-white">
      <h3 class="text-lg font-semibold mb-4">Counter Component</h3>
      <p class="text-gray-600 mb-4">This is a client component with state and interactivity.</p>

      <div class="flex items-center gap-4 mb-4">
        <button
          onClick$={() => count.value--}
          type="button"
          class="px-3 py-1 bg-red-500 text-white rounded hover:bg-red-600 transition-colors"
        >
          -
        </button>

        <span class="text-2xl font-bold text-blue-600 min-w-8 text-center">{count.value}</span>

        <button
          onClick$={() => count.value++}
          type="button"
          class="px-3 py-1 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
        >
          +
        </button>
      </div>

      <div class="text-sm text-gray-500">
        <p>• This component uses React hooks (useState)</p>
        <p>• It has event handlers (onClick)</p>
        <p>• It should run on the client, not the server</p>
      </div>
    </div>
  )
})
